- name: get command output
  shell: |
    set -o pipefail
    journalctl -u substrate --no-pager > /root/substrate.log
    tail -n 10000 /root/substrate.log | grep "Waiting to import block"
  become: yes
  args:
    executable: /bin/bash
  changed_when: False
  register: command_output

- name: result
  debug:
    msg: "Command result: {{ command_output.stdout }}"

- name: remove log
  file:
    path: /root/substrate.log
    state: absent
